[versions]
agp = "8.6.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.2"
constraintlayout = "2.1.4"
playServicesLocation = "21.3.0"
room = "2.6.1"
robolectric = "4.10"
mockito = "5.2.0"
retrofit = "2.9.0"           # A침adimos la versi칩n de Retrofit
gsonConverter = "2.9.0"      # A침adimos la versi칩n del convertidor Gson

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.2" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Retrofit y Gson Converter
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "gsonConverter" }

# Dependencias de pruebas
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockitoAndroid = { group = "org.mockito", name = "mockito-android", version.ref = "mockito" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
